[project]
name = "ytdl-gui"
version = "0.1.0"
description = "A threaded Tkinter video and audio downloader powered by yt-dlp"
readme = "README.md"
authors = [
    { name = "meachsenbroseth", email = "153406625+meachsenbroseth@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pillow>=12.3.0",
    "yt-dlp[default]>=2026.8.19",
]

[project.scripts]
ytdl-gui = "ytdl_gui.__main__:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pyinstaller>=6.22.3",
]
